### ISSUE TITLE
Is there any example on usage?

### ISSUE THREAD

**Issue by cryptid11** [rodrigo-weigert/ImgTamperingDetection#1]
I'd like to see them, atm I'm quite confused :D

**Comment by rodrigo-weigert** [comment]
Yes there is. In ``code/classifier/results`` there are a couple of directories containing data on some tests we did, and those include ``README.txt`` files [like this one](https://github.com/rodrigo-weigert/ImgTamperingDetection/blob/299b3d5c21b36bde5f042780e292e24b1cab3402/code/classifier/results/Gaussian_1000/README.txt) with the step by step explation on how to reproduce the result.

Please note though that the repo name is a bit misleading. What we did is still pretty far from actually detecting *all* forms of digital tampering in a reliable way - this is a hard problem. Also unfortunately since this project was done as an assignment for an image processing class, we didn't really have time to focus on usability. Everything is indeed confusing and kind of inconvenient to use. For instance, currently there's no way to test single images and see the results. Lots of things should be improved. This project probably wouldn't even have made it into GitHub, if this wasn't a requirement from our teacher.

**Comment by cryptid11** [comment]
Thanks, I understand, but on the contrary it seems pretty difficult to find good sources and examples so I think you should double down on effort to make this public and make a little blog post where you give the basics to explain what are you actually training and how. I'll would like this a lot!

Meanwhile, I know the basics of the field since I follow a whole conference on the matter by very reputable persons in the field, and - I know is difficult problem - but is there a trained classifier out there who make several test on image use can provide to classifier? 

Thanks in advance to any hint in the matter.

**Comment by rodrigo-weigert** [comment]
I appreciate your interest in this humble, messy assignment. I could try and tidy it up. If/when I have time to spare, I might, but for now I won't make any promises. Anyway, if it helps: what was implemented is pretty much the method described in [this 2005 paper](https://www.researchgate.net/publication/228937279_Image_manipulation_detection_with_binary_similarity_measures), with only a few small differences and a [different, larger dataset](http://forensics.idealtest.org/casiav2/) (the website seems to be down right now) for training and testing. Additionally we didn't perform exactly all the tests described on the paper, only a few similar ones.

As for your question, I don't know if I understood it correctly. If you're talking about this project, then no, currently our implementation cannot test arbitrary images provided by the user. Implementing this would be among the top itens on the TODO list for tidying up this project. It is definitely feasible, but it would require quite a bit of changes and additions to the current source codes.

**Comment by cryptid11** [comment]
Thanks for links I look forward to future comments here if you post something about this!

Also yes, I'm searching for a "image verifier" already trained, I will ask some professor, will be right back here with results if any.

Thanks a lot meanwhile :))))

**Comment by rodrigo-weigert** [comment]
> Also yes, I'm searching for a "image verifier" already trained, I will ask some professor, will be right back here with results if any.

I see. I have no knowledge of anything like this being available anywhere, but I didn't look for it.
If I do implement something like this, it'll be for detecting very simple digital editions, like blurring of the entire image. Our classifier isn't accurate enough for more complex tampering.

I'm kinda busy this week and the next, but maybe I can do something until the end of the month. I'll see.

**Comment by cryptid11** [comment]
> I see. I have no knowledge of anything like this being available anywhere, but I didn't look for it.

Yes, professor says the same, that is the bigger aim of actual research it seems, but they still have to work on that.

>I'm kinda busy this week and the next, but maybe I can do something until the end of the month. I'll see.

Wow thanks for that!

**Comment by rodrigo-weigert** [comment]
Made a simple demo program, be sure to check it out =)
Details are in the repo readme.

**Comment by cryptid11** [comment]
Is there a missing dependency I can't figure it out how to install, it's named cv2.

**Comment by rodrigo-weigert** [comment]
This is OpenCV. Annoyingly, it's a requirement for everything to work. Here's an installation guide.
http://cyaninfinite.com/tutorials/installing-opencv-in-ubuntu-for-python-3/
